// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[slug].get').default>>>>
    }
    '/api/categories/:slug/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[slug]/products.get').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products.get').default>>>>
    }
    '/api/products/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
    }
    '/api/recommendations/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recommendations/[slug].get').default>>>>
    }
    '/api/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}